### ISSUE TITLE
Add multinomial version of credit card notebook (monotonic XGBoost, PDP, ICE, & Shapley)

### ISSUE THREAD

**Issue by navdeep-G** [navdeep-G/interpretable-ml#4]
Follow same outline here but for multinomial prediction: https://github.com/navdeep-G/interpretable-ml/blob/master/notebooks/credit/xgb_credit_binary_classifier.ipynb
* [x] Need multinomial XGBoost model with monotonicity constraints
* [x] Need variable importance from model
* [x] Need Shapley values per class outcome
* [x] Need global Shapley variable importance
* [x] Need local Shapley example
* [x] PDP (partial dependence per class outcome)
* [x] ICE (ICE values per class outcome)

**Comment by jphall663** [comment]
My advice here is ...  (see what you think)
1. GENERAL 
- [ ] scrap monotonic (since it is broken/unsupported).
2. GLOBAL VAR. IMP.
- [ ] do not use XGBoost var. imp. (it's theoretically inconsistent).
- [ ] use mean absolute shapley across all classes and rows as overall var. imp. ranking then just make a horizontal bar chart of the above values for each var. for overall var. imp. across all classes. (Should look like XGBoost var. imp. chart.) 
- [ ] Then break shapley out by class using shap package summary plot, like you did for PAY_0 = 0, but just repeat for all classes. 
3. LOCAL VAR. IMP. (show for 2-3 rows)
- [ ] show mean absolute shapley ranking across classes for each variable as horizontal bar chart for a single row. (should look like global var. imp. horizontal bar chart above.)
- [ ] show regular signed shapley values and reason codes for the class that the model predicts.
4. PDP/ICE 
- [ ] Keep overall PDP plot you have, but make a point that if classes > 10, we would only take the top 10 most common classes by default. 
- [ ] For ICE, plot at min, max, and deciles as we've done before, but now we have to do it for each class. Also keep partial dependence in ICE plot and plot ice curves in a color gradient of the same color as the corresponding partial dependence. So ICE for class=0 would be all blue gradients, for class=1 it would be all orange color gradients, and so on.
5. Surrogate DT. 
- [ ] Find some package, even if it's R, that does multinomial decision tree for one overall surrogate DT. This can be in a different notebook. 
- [ ] For surrogate DT be sure to show overall error and CV error.

**Comment by jphall663** [comment]
For local var. imp.:
- [ ] do like we originally did for multinomial loco, just mean absolute shapley value across all classes for each variable. 
- [ ] then make reason codes with shapley the way we have been doing, but only for the predicted class. not all classes. 

Please try to find a single, multinomial DT. I promise this is the most elegant way to handle. It will show how to get to probabilities in each class, but in a single tree. We have to summarize info to be useful/novel. Per class surrogate DT is ok too, but I would only show those after showing a single DT, like this one:  
![selection_019](https://user-images.githubusercontent.com/5297912/45909144-3d0d6200-bdce-11e8-8f01-4ec0ba3680d2.png)

**Comment by navdeep-G** [comment]
Okay, makes sense. The DT surrogate would be all features with the outcome being the predicted class.

**Comment by navdeep-G** [comment]
Moved DT surrogate comments here: https://github.com/navdeep-G/interpretable-ml/issues/5

**Comment by navdeep-G** [comment]
I think I have addressed all of your comments from a code standpoint.
